### ISSUE TITLE
Web app stops working after adding nativescript app

### ISSUE THREAD

**Issue by Guilherhast** [NativeScript/nx#25]
I tested the webserver and it was working fine.

I ran the command:
`npx nx g @nativescript/nx:app myApp --groupByName --framework angular`

After this the web server throws an error:

```

<rootdir>/node_modules/@angular/compiler-cli/src/typescript_support.js:65
            throw new Error("The Angular Compiler requires TypeScript >=" + minVersion + " and <" + maxVersion + " but " + version + " was found instead.");
            ^

Error: The Angular Compiler requires TypeScript >=4.0.0 and <4.2.0 but 4.2.4 was found instead.
    at checkVersion (<rootdir>/node_modules/@angular/compiler-cli/src/typescript_support.js:65:19)
    at Object.verifySupportedTypeScriptVersion (<rootdir>/node_modules/@angular/compiler-cli/src/typescript_support.js:70:9)
    at new NgtscProgram (<rootdir>/node_modules/@angular/compiler-cli/src/ngtsc/program.js:44:38)
    at AngularWebpackPlugin.updateAotProgram (<rootdir>/node_modules/@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/ivy/plugin.js:277:32)
    at <rootdir>/node_modules/@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/ivy/plugin.js:167:24
    at Hook.eval [as call] (eval at create (<rootdir>/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:20:1)
    at Hook.CALL_DELEGATE [as _call] (<rootdir>/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (<rootdir>/node_modules/webpack/lib/Compiler.js:1030:30)
    at <rootdir>/node_modules/webpack/lib/Compiler.js:1073:29
    at Hook.eval [as callAsync] (eval at create (<rootdir>/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (<rootdir>/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (<rootdir>/node_modules/webpack/lib/Compiler.js:1068:28)
    at <rootdir>/node_modules/webpack/lib/Watching.js:134:19
    at Hook.eval [as callAsync] (eval at create (<rootdir>/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (<rootdir>/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at run (<rootdir>/node_modules/webpack/lib/Watching.js:88:33)

```

My nx report is:

```

>  NX  Report complete - copy this into the issue template

  Node : 15.13.0
  OS   : linux x64
  yarn : 1.22.5
  
  nx : Not Found
  @nrwl/angular : 12.3.3
  @nrwl/cli : 12.3.3
  @nrwl/cypress : 12.3.3
  @nrwl/devkit : 12.3.3
  @nrwl/eslint-plugin-nx : 12.3.3
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.3
  @nrwl/linter : 12.3.3
  @nrwl/nest : 12.3.3
  @nrwl/next : Not Found
  @nrwl/node : 12.3.3
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.3
  @nrwl/web : Not Found
  @nrwl/workspace : 12.3.3
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

```

**Comment by mahmoudajawad** [comment]
That is expected behaviour as (as of May 5th., 21) `latest` tag of `create-nx-workspace` is creating a workspace compatible with Angular 12, while `@nativescript/nx` is still at Angular 11. I'm using npm, not `yarn, and it prevents me from using `@nativescript/nx` in Angular 12 Nx workspace, so maybe it is something yarn couldn't catch?

Anyway, you either wait for Angular-12-compatible `@nativescript/angular`, `@nativescript/nx` packages which seem to be very imminent, or you downgrade your workspace and web-app to Angular 11, which I wouldn't do.
