### ISSUE TITLE
[Q] How can lib generator be used to create NS plugins?

### ISSUE THREAD

**Issue by mahmoudajawad** [NativeScript/nx#26]
I'm trying to create a plugin to be used across two apps in the workspace. The plugin requires native libs, so simply using `lib` generator doesn't seem to create structure to allow me to add native libs. I tried to configure `tsconfig`, but it seems without having a package definition at the lib-level, building a plugin won't be possible, and I'm not sure how that can be achieved.

**Comment by mahmoudajawad** [comment]
I tried this and it didn't work, which makes me wonder how do these things work:
- Created new Nx workspaces.
- Cloned `https://github.com/NativeScript/plugin-seed`.
- Copied the following files to the new Nx workspaces:
  - `nx.json`.
  - `package.json`.
  - `tsconfig.base.json`.
  - `workspace.json`.
- Ran `npm run config && npm run setup`.
- Got the following:
```
SyntaxError: Unexpected token } in JSON at position 308
    at JSON.parse (<anonymous>)
    at jsonParse (/path/to/workspaces/node_modules/@nativescript/plugin-tools/src/utils/workspace.js:64:21)
    at Object.getJsonFromFile (/path/to/workspaces/node_modules/@nativescript/plugin-tools/src/utils/workspace.js:58:12)
    at /path/to/workspaces/node_modules/@nativescript/plugin-tools/src/schematics/config/index.js:35:54
    at MergeMapSubscriber.project (/path/to/workspaces/node_modules/@angular-devkit/schematics/src/rules/call.js:75:24)
    at MergeMapSubscriber._tryNext (/path/to/workspaces/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:67:27)
    at MergeMapSubscriber._next (/path/to/workspaces/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (/path/to/workspaces/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Observable._subscribe (/path/to/workspaces/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/util/subscribeToArray.js:5:20)
    at Observable._trySubscribe (/path/to/workspaces/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Observable.js:44:25)
Unexpected token } in JSON at position 308
```

**Comment by mahmoudajawad** [comment]
I updated the error message (in previous comment) after I found that one of the child apps `tsconfig.json` is the reason behind the previous parsing error, however, another error came up, and though I tried hunting it down at `@nativescript/build-tools/src/generators/add-package`, I failed as it expects to have a demo app in the workspace, and without it, the plugin package won't be created. I hope to give this more time in the coming days to figure out a recipe that allows me to get it working.
